### ISSUE TITLE
Problem defining notification command and strange output

### ISSUE THREAD

**Issue by joncolas** [mmarodin/icinga2-plugins#1]
Hello! i tried to setup icinga2 notifications using your python script but i found various problems, when I defined the commands.conf and python script files as you have, icinga2 debug log shows this error:

`[2016-10-10 10:14:30 +0000] warning/PluginNotificationTask: Notification command for object 'icinga2-10-0-0-89!apt' (PID: 8866, arguments: '/etc/icinga2/scripts/mail-service-perfdata-notification.py') terminated with exit code 128, output: execvpe(/etc/icinga2/scripts/mail-service-perfdata-notification.py) failed: No such file or directory`

Then i changed python script shebang:
from this `#!/bin/python`
to `#!/usr/bin/env python`

`[2016-10-10 10:36:56 +0000] notice/Process: PID 20609 ('/etc/icinga2/scripts/mail-service-perfdata-notification.py') terminated with exit code 0`

Then notices began to arrive, but as shown in the picture below, Any idea what could be going on?
![screenshot at 12-24-28](https://cloud.githubusercontent.com/assets/8049798/19233476/fc5e97ec-8ee5-11e6-93f6-0ae968110ebc.png)

Greetings and thanks!

**Comment by joncolas** [comment]
Some interesting info
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.5.4-1)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.3 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.13.0-77-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.4
  Build host: lgw01-18
```
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by mmarodin** [comment]
Probably you have to check the HTML built into the script, it has to 
include valid URLs codes.
And you have to enable into Grafana an API user that could generate 
static graphs without authentication.

I think this could be your problem.
Let me know, bye

Il 10/10/16 12:40, joncolas ha scritto:

**Comment by mmarodin** [comment]
See the picture attached. Sorry, you have to define an API key, not a user

Il 10/10/16 12:40, joncolas ha scritto:

**Comment by joncolas** [comment]
Thanks for reply, when creating APIKey I guess that will be enough with the role of viewer, right  ?
![screenshot at 11-37-16](https://cloud.githubusercontent.com/assets/8049798/19382979/c2b984e6-9202-11e6-9bbe-bd0f38b692ac.png)

**Comment by joncolas** [comment]
What I should fill here?

GRAFANAVARHOST = 'var-HOST'
GRAFANAVARSERVICE = 'var-SERVICE'

Greetings

**Comment by mmarodin** [comment]
About Grafana APIKEY:

/http://docs.grafana.org/reference/http_api///
//http://docs.grafana.org/http_api/auth//

About Grafana variables you have to set them in your Dashboard:

/http://docs.grafana.org/reference/templating//

Then try to call a graph manually using this URL 
.../render/dashboard-solo/db/...


Il 14/10/16 11:53, joncolas ha scritto:

**Comment by joncolas** [comment]
What are those custom vars?

[2016-10-18 17:14:19 +0000] warning/MacroProcessor: Macro 'host.vars.host_url' is not defined.
Context:
	(0) Resolving macros for string '**$host.vars.host_url$**'

[2016-10-18 17:14:19 +0000] warning/MacroProcessor: Macro 'host.vars.panel_url' is not defined.
Context:
	(0) Resolving macros for string '**$host.vars.panel_url$**'


Regards

**Comment by joncolas** [comment]
i think `host.vars.host_url` and `host.vars.panel_url` are hostname and panel id in graphana, right?

**Comment by mmarodin** [comment]
Yes!

Il 19/10/16 10:13, joncolas ha scritto:
