### ISSUE TITLE
Add arguments to the notification scripts

### ISSUE THREAD

**Issue by ktella** [mmarodin/icinga2-plugins#2]
Hey notification scripts are awesome. 

Is it possible to develop a same set of notification scripts to take arguments instead of Macros.

**Comment by mmarodin** [comment]
You could fork my script and create a new one :)
Icinga2 notification scripts are using Macros too

**Comment by mmarodin** [comment]
@ktella from the start of 2019 my notification scripts have been supporting arguments 👍 
Sorry for the missed information :)
