### ISSUE TITLE
Service Notification Error

### ISSUE THREAD

**Issue by ntrie** [mmarodin/icinga2-plugins#3]
Hi!
love your script so far and the notification for the Host are working great!

(unfortunatly the render PNG is blank but thats a pProblem of Grafana)

If i try to send Service notifications the icinga log shows the following,
are I missing something?

>> ValueError: need more than 1 value to unpack

thanks

`[2017-02-21 14:59:24 +0100] information/ExternalCommandListener: Executing external command: [1487685564] SEND_CUSTOM_SVC_NOTIFICATION;TESTSERVER;Drive Space C;0;admin;test
[2017-02-21 14:59:24 +0100] information/Checkable: Checking for configured notifications for object 'TESTSERVER!Drive Space C'
[2017-02-21 14:59:24 +0100] information/Notification: Sending 'Custom' notification 'TESTSERVER!Drive Space C!mail-icingaadmin-test for user 'testuser'
[2017-02-21 14:59:24 +0100] information/Notification: Completed sending 'Custom' notification 'TESTSERVER!Drive Space C!mail-icingaadmin-test' for checkable 'TESTSERVER!Drive Space C' and user 'testuser'.
[2017-02-21 14:59:24 +0100] warning/PluginNotificationTask: Notification command for object 'TESTSERVER!Drive Space C' (PID: 25690, arguments: '/etc/icinga2/scripts/mail-service-perfdata-notification.py') terminated with exit code 1, output: Traceback (most recent call last):
  File "/etc/icinga2/scripts/mail-service-perfdata-notification.py", line 106, in <module>
    (LABEL,DATA) = PERFDATA.split("=")
ValueError: need more than 1 value to unpack`

**Comment by mmarodin** [comment]
I've just pushed the fix for this problem.
Please try it and then let me know! ;)

**Comment by ntrie** [comment]
Thanks for the effort. Changed user customization and my bin/python path but got the same error :(
Something wrong on my side?


`[2017-02-24 12:52:27 +0100] information/Notification: Sending 'Custom' notification 'TESTSERVER!Drive Space C!mail-icingaadmin-test for user 'testuser'
[2017-02-24 12:52:27 +0100] information/Notification: Completed sending 'Custom' notification 'TESTSERVER!Drive Space C!mail-icingaadmin-test' for checkable 'TESTSERVER!Drive Space C' and user 'testuser'.
[2017-02-24 12:52:27 +0100] warning/PluginNotificationTask: Notification command for object 'TESTSERVER!Drive Space C' (PID: 28254, arguments: '/etc/icinga2/scripts/mail-service-perfdata-notification.py') terminated with exit code 1, output: Traceback (most recent call last):
  File "/etc/icinga2/scripts/mail-service-perfdata-notification.py", line 106, in <module>
    (LABEL,DATA) = PERFDATA.split("=")
ValueError: need more than 1 value to unpack`

**Comment by mmarodin** [comment]
Could you please send me the output of the check plugin?

Like:
> & 'C:\Program Files\ICINGA2\sbin\check_disk.exe' -p C: -w 20% -c 10%
> DISK OK - free space:c:\ 34737397760 B (65%); | c:\=34737397760B;10663597670.400002;5331798835.2000008;0;53317988352

Please let me know, bye

**Comment by ntrie** [comment]
I'm using check_nt right now and looks like this

`/usr/lib/nagios/plugins# ./check_nt -H 10.10.10.11 -p 12489 -s#remote# -v USEDDISKSPACE -l c -w 90 -c 98

c:\ - total: 40,00 Gb - used: 22,11 Gb (55%) - free 17,89 Gb (45%) | 'c:\ Used Space'=22,11Gb;36,00;39,20;0.00;40,00`

**Comment by mmarodin** [comment]
Have you added the custom ENV variable into the _object NotificationCommand_ configuration?
> SERVICEPERFDATA = "$service.perfdata$"

Could you try to print the value of the variable into a textfile to see it after the execution of the script?

Please let me know, thanks

**Comment by ntrie** [comment]
I copied your _NotificationCommand_ for host and service, so yes the ENV variable is in the command conf.
But i got no perfdata set in my service check, so variable should be empty 

I also got no perfdata in my the host object and that notification works fine

**Comment by mmarodin** [comment]
Sorry, but only this service check has the problem of all checks?

**Comment by ntrie** [comment]
well ... yes.
Tested the standard ping4 check and works just fine. Email + Perfdata + PNG from Grafana
Maybe i should use a different check command :)

ping4 perfdata:
`rta=0.396000ms;100.000000;200.000000;0.000000 pl=0%;5;15;0`

thanks

**Comment by mmarodin** [comment]
Let's do a try to Icinga2 plugins for Windows, I'm using them, they are nice.
And I wrote some custom PowerShell plugins, and I use them via Icinga2 plugins for Windows.
You can find them here:
https://github.com/mmarodin/icinga2-plugins/tree/master/windows

**Comment by MuskratAggie** [comment]
Howdy!  Beautiful notifications you have here...thanks for sharing them!!!  I too am having this issue with the check_wmi_plus.pl plugin, but only with certain modes/submodes.  I updated to the latest version of both.  When I try to send a test email, and the (for example) RDP Sessions for a server is in an OK state, I get:

[2017-03-30 16:03:07 -0500] warning/PluginNotificationTask: Notification command for object '<servername>!RDP Sessions' (PID: 36703, arguments: '/etc/icinga2/scripts/mail-service-perfdata-notification.py') terminated with exit code 1, output: Traceback (most recent call last):
  File "/etc/icinga2/scripts/mail-service-perfdata-notification.py", line 110, in <module>
    (VALUE,WARNING,CRITICAL,MIN) = DATA.split(";")
ValueError: need more than 2 values to unpack

In this same sense, I was getting the CRITICAL and UNKNOWN notifications, but not the RECOVERY or OK.  What else is it looking for?

Thanks again for sharing this beautiful notification!!!

**Comment by mmarodin** [comment]
Could you please send me the output of the check plugin runned manually from bash?
Thanks

**Comment by MuskratAggie** [comment]
Here you go, thanks again!!

# ./check_wmi_plus.pl -H <hostname> -A /etc/icinga2/wmi.auth -m checkts -s sessions -w "ActiveSessions=0 -w TotalSessions=1" -c "ActiveSessions=1 -c TotalSessions=2"

OK - ActiveSessions=0, InactiveSessions=3, TotalSessions=3|'ActiveSessions'=0;0;1; 'InactiveSessions'=3; 'TotalSessions'=3;

**Comment by mmarodin** [comment]
Hi MuskratAggie, sorry for the delay in my feedback.
Are you sure you are using the last version of this script? I've just checked manually it using performance data that you posted here (_'ActiveSessions'=0;0;1; 'InactiveSessions'=3; 'TotalSessions'=3;_) and it works.

Please see this python example:
`# python
Python 2.7.5 (default, Sep  5 2016, 02:30:38)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> # Set my variables:
... WIDTH = '640'
>>> COLUMN = '144'
>>> DIFFERENCE = str(int(WIDTH) - int(COLUMN))
>>> HTML = ""
>>>
>>> # Set your specific Performance Data:
... SERVICEPERFDATA = "'ActiveSessions'=0;0;1; 'InactiveSessions'=3; 'TotalSessions'=3;"
>>>
>>> # Part of my script:
... #...
... if (SERVICEPERFDATA or PANELURL):
...   #HTML += '\n</table><br>'
...   HTML += '\n<table width=' + WIDTH + '>'
...   HTML += '\n<tr><th colspan=6 class=perfdata>Performance Data</th></tr>'
...   if (SERVICEPERFDATA):
...     HTML = '\n<tr><th>Label</th><th>Last Value</th><th>Warning</th><th>Critical</th><th>Min</th><th>Max</th></tr>'
...     PERFDATALIST = SERVICEPERFDATA.split(" ")
...     for PERFDATA in PERFDATALIST:
...       (LABEL,DATA) = PERFDATA.split("=")
...       if (len(DATA.split(";")) is 5):
...         (VALUE,WARNING,CRITICAL,MIN,MAX) = DATA.split(";")
...       if (len(DATA.split(";")) is 4):
...         (VALUE,WARNING,CRITICAL,MIN) = DATA.split(";")
...         MAX = ''
...       if (len(DATA.split(";")) is 3):
...         (VALUE,WARNING,CRITICAL) = DATA.split(";")
...         MAX = ''
...         MIN = ''
...       if (len(DATA.split(";")) is 2):
...         (VALUE,WARNING) = DATA.split(";")
...         MAX = ''
...         MIN = ''
...         CRITICAL = ''
...       if (len(DATA.split(";")) is 1):
...         VALUE = DATA
...         MAX = ''
...         MIN = ''
...         CRITICAL = ''
...         WARNING = ''
...       HTML += '\n<tr><td>' + LABEL + '</td><td>' + VALUE + '</td><td>' + WARNING + '</td><td>' + CRITICAL + '</td><td>' + MIN + '</td><td>' + MAX + '</td></tr>'
...   else:
...     HTML += '\n<tr><th width=' + COLUMN + ' colspan=1>Last Value:</th><td width=' + DIFFERENCE + ' colspan=5>none</td></tr>'
... #...
...
>>> # Print result:
... print HTML

<tr><th>Label</th><th>Last Value</th><th>Warning</th><th>Critical</th><th>Min</th><th>Max</th></tr>
<tr><td>'ActiveSessions'</td><td>0</td><td>0</td><td>1</td><td></td><td></td></tr>
<tr><td>'InactiveSessions'</td><td>3</td><td></td><td></td><td></td><td></td></tr>
<tr><td>'TotalSessions'</td><td>3</td><td></td><td></td><td></td><td></td></tr>
>>>`

I think that you are using a previos release of my script or there is a problem in your performance data syntax.
Please let me know, bye
